### ISSUE TITLE
clean up all committed migrations and migration code from the code base

### ISSUE THREAD

**Issue by sivang** [ZviBaratz/pylabber#29]
I have realized where the problem with recurrent migrations we have: They are committed into the GIT tree. We need to clean this up. The only thing that should be pushed is plain code nothing else.

**Comment by ZviBaratz** [comment]
Resolved in commits ZviBaratz/pylabber@fcee4a58b19b8eef027a1b23b005ccb7297c208e, ZviBaratz/django_mri@084b9b7cdc16d36fae5f42881c585728ea9bf428, and ZviBaratz/django_dicom@875afdd2f885cca2b5ced4d0c32bf171f1eaf081.
