### ISSUE TITLE
Allow remote access to the application

### ISSUE THREAD

**Issue by ZviBaratz** [ZviBaratz/pylabber#8]
Learn how to expose a port and allow people to connect to the application through the server.

**Comment by ZviBaratz** [comment]
Create a service that runs and serves the application from the server.

**Comment by ZviBaratz** [comment]
Uni IT have a created a proxy in front of the server for outside connections. We just need to secure the connection using SSL.

**Comment by sivang** [comment]
We've moved to host on a cloud provider.
